namespace YoutubeExplode.Models
{
    /// <summary>
    /// Youtube video subtitles meta data
    /// </summary>
    public class VideoCaptionTrackInfo
    {
        /// <summary>
        /// URL of the caption track manifest file
        /// </summary>
        public string Url { get; internal set; }

        /// <summary>
        /// Language of this caption track
        /// </summary>
        public string Language { get; internal set; }

        /// <summary>
        /// Whether this caption track was generated automatically
        /// </summary>
        public bool IsAutoGenerated { get; internal set; }

        internal VideoCaptionTrackInfo() { }

        /// <inheritdoc />
        public override string ToString()
        {
            if (IsAutoGenerated)
                return $"{Language} (auto)";
            return $"{Language}";
        }
    }
}